language: go
# go:
#   - 1.9.x
env:
  - secure: ""

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - rm -f main.go

install:
  - true

script:
    - cd jobber;go test -v -covermode=count -coverprofile=coverage.out .
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
